# Please use a personal access token given by Github.
# Help here: https://iamnaran.medium.com/fixed-support-for-password-authentication-was-removed-628faf76057
token = 'REPLACE_HERE_WITH_YOUR_TOKEN'
